-- Seed data: 22 Major Arcana tarot cards.
-- Run this AFTER schema.sql. Safe to re-run (upsert on card_name).

insert into public.tarot_cards (card_name, arcana, upright_meaning, reversed_meaning, keywords)
values
  ('The Fool', 'major',
   'New beginnings, spontaneity, a leap of faith into the unknown.',
   'Recklessness, hesitation, a fear of taking the first step.',
   array['beginnings','freedom','innocence','potential']),
  ('The Magician', 'major',
   'Personal power, manifestation, focused action on a clear intention.',
   'Scattered energy, manipulation, untapped talent.',
   array['willpower','skill','manifestation','focus']),
  ('The High Priestess', 'major',
   'Intuition, inner knowing, quiet attention to subtle signals.',
   'Secrets, blocked intuition, ignoring the inner voice.',
   array['intuition','mystery','subconscious','stillness']),
  ('The Empress', 'major',
   'Abundance, nurturing, creative flow and sensory aliveness.',
   'Creative block, overextension, neglecting self-care.',
   array['abundance','care','nature','creation']),
  ('The Emperor', 'major',
   'Structure, steady authority, discipline that creates safety.',
   'Rigidity, control, leadership without compassion.',
   array['structure','authority','stability','order']),
  ('The Hierophant', 'major',
   'Tradition, mentorship, learning inside an established system.',
   'Breaking rules, questioning dogma, unconventional path.',
   array['tradition','mentor','community','values']),
  ('The Lovers', 'major',
   'Alignment, meaningful choice, union of values and action.',
   'Misalignment, indecision, relationships out of sync.',
   array['choice','union','alignment','values']),
  ('The Chariot', 'major',
   'Willed momentum, disciplined pursuit of a clear goal.',
   'Stalled drive, opposing forces pulling in two directions.',
   array['drive','control','victory','direction']),
  ('Strength', 'major',
   'Calm courage, patient persistence, gentle mastery of impulses.',
   'Self-doubt, impatience, inner tension overriding steadiness.',
   array['courage','patience','compassion','inner-power']),
  ('The Hermit', 'major',
   'Reflection, solitude, quiet search for deeper understanding.',
   'Isolation, withdrawal, refusing help.',
   array['introspection','solitude','wisdom','search']),
  ('Wheel of Fortune', 'major',
   'Turning points, cycles, accepting the rhythm of change.',
   'Resisting change, bad timing, feeling stuck in a loop.',
   array['cycles','change','fate','momentum']),
  ('Justice', 'major',
   'Honest consequences, clarity, decisions made with fairness.',
   'Avoidance, imbalance, refusing accountability.',
   array['truth','fairness','consequence','clarity']),
  ('The Hanged Man', 'major',
   'Pause, new perspective, surrender that reveals a way forward.',
   'Stagnation, stubbornness, refusal to let go.',
   array['perspective','pause','surrender','insight']),
  ('Death', 'major',
   'Transformation, clean endings, making space for what is next.',
   'Clinging, fear of change, a transition incomplete.',
   array['transformation','ending','release','renewal']),
  ('Temperance', 'major',
   'Balance, patient blending, finding the middle way.',
   'Imbalance, excess, trying to force a rhythm.',
   array['balance','moderation','healing','flow']),
  ('The Devil', 'major',
   'Awareness of attachment, naming what binds you.',
   'Breaking a cycle, reclaiming agency, stepping out of fear.',
   array['attachment','shadow','patterns','awareness']),
  ('The Tower', 'major',
   'Sudden revelation, structures falling to reveal truth.',
   'Narrowly avoided disruption, delayed reckoning.',
   array['revelation','change','shock','truth']),
  ('The Star', 'major',
   'Hope, quiet renewal, trust in a clearer future.',
   'Discouragement, lost faith, disconnection from inspiration.',
   array['hope','healing','faith','renewal']),
  ('The Moon', 'major',
   'Uncertainty, dreamlike intuition, navigating in partial light.',
   'Dissolving illusions, confusion lifting, clarity returning.',
   array['intuition','uncertainty','dreams','emotion']),
  ('The Sun', 'major',
   'Vitality, clarity, warm confidence in what is true.',
   'Dimmed joy, temporary setback, needing to reconnect with play.',
   array['joy','success','vitality','clarity']),
  ('Judgement', 'major',
   'Reckoning, awakening, answering an inner call.',
   'Self-doubt, ignoring the call, harsh self-judgment.',
   array['awakening','calling','reflection','release']),
  ('The World', 'major',
   'Completion, integration, wholeness after a full cycle.',
   'Unfinished work, loose ends, a chapter not yet closed.',
   array['completion','integration','achievement','wholeness'])
on conflict (card_name) do update set
  arcana = excluded.arcana,
  upright_meaning = excluded.upright_meaning,
  reversed_meaning = excluded.reversed_meaning,
  keywords = excluded.keywords;
